import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {  Providers } from "./providers";
import Footer from './_components/footer';
import './globals.css'
import { Header } from './components/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <body>
        <Header/>
        <Providers>
          {children}
        </Providers>

        <Footer />
      </body>
    </html>
  );
}