import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {  Providers } from "./providers";
import { AppProps } from 'next/app';
import './globals.css'
import Footer from './_components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rifacil',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
          {children}
        </Providers>

        <Footer />
      </body>
    </html>
  );
}